services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
    #Twig\Extensions\ArrayExtension: ~


    # Uncomment any lines below to activate that Twig extension
    #Twig\Extensions\ArrayExtension: ~
    Twig\Extensions\DateExtension: ~
    #Twig\Extensions\IntlExtension: ~
    #Twig\Extensions\TextExtension: ~
